### ISSUE TITLE
devcontainer up fails with docker-compose +features and latest docker

### ISSUE THREAD

**Issue by NigelRook** [devcontainers/cli#433] opened 2023-03-03 14:19 UTC
I'm getting the following error when running `devcontainer up --workspace-folder . --log-level debug`:

```
<snip...>
[551 ms] name: devcontainer
services:
  app:
    command:
    - sleep
    - infinity
    image: ubuntu:20.04
    networks:
      default: null
networks:
  default:
    name: devcontainer_default
[552 ms] Start: Run: docker inspect --type image ubuntu:20.04
[600 ms] local container features stored at: /home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/node_modules/vscode-dev-containers/container-features
[601 ms] Start: Run: tar --no-same-owner -x -f -
[628 ms] * Processing feature: ghcr.io/devcontainers/features/docker-outside-of-docker:1
[1493 ms] * Fetching feature: docker-outside-of-docker_1_oci
[2166 ms] Start: Run: docker build -t dev_container_feature_content_temp -f /tmp/devcontainercli-nrook/container-features/0.31.0-1677852671737/Dockerfile.buildContent /tmp/devcontainercli-nrook/container-features/0.31.0-1677852671737
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 0.1s (4/4) FINISHED                                                
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile.buildContent          0.0s
 => => transferring dockerfile: 95B                                        0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 326.26kB                                      0.0s
 => CACHED [1/1] COPY . /tmp/build-features/                               0.0s
[2507 ms] Docker Compose override file for building image:
version: '3'

services:
  app:
    image: vsc-devcontainer-issues-763e9562f651ec7f1835a7a9ef03a2c6
    build:
      dockerfile: /tmp/devcontainercli-nrook/container-features/0.31.0-1677852671737/Dockerfile-with-features
      context: /tmp/devcontainercli-nrook/empty-folder
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label
        - _DEV_CONTAINERS_IMAGE_USER=root
        - _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp

[2508 ms] Start: Run: docker compose --project-name devcontainer-issues_devcontainer -f /home/nrook/dev/personal/devcontainer-issues/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-nrook/docker-compose/docker-compose.devcontainer.build-1677852673644.yml build --no-cache
[+] Building 0.7s (5/5) FINISHED                                                
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 1.80kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/dev_container_fe  0.7s
 => [internal] load metadata for docker.io/library/ubuntu:20.04            0.5s
 => [auth] library/dev_container_feature_content_temp:pull token for regi  0.0s
------
 > [internal] load metadata for docker.io/library/dev_container_feature_content_temp:latest:
------
failed to solve: dev_container_feature_content_temp: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: Command failed: docker compose --project-name devcontainer-issues_devcontainer -f /home/nrook/dev/personal/devcontainer-issues/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-nrook/docker-compose/docker-compose.devcontainer.build-1677852673644.yml build --no-cache
    at yF (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1896:412)
    at async sie (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1896:2381)
    at async iie (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1878:2396)
    at async xie (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1945:2798)
    at async Wf (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1945:3750)
    at async noe (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:17325)
    at async roe (/home/nrook/.fnm/node-versions/v14.18.1/installation/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:17066)
{"outcome":"error","message":"Command failed: docker compose --project-name devcontainer-issues_devcontainer -f /home/nrook/dev/personal/devcontainer-issues/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-nrook/docker-compose/docker-compose.devcontainer.build-1677852673644.yml build --no-cache","description":"An error occurred building the Docker Compose images."}
```

.devcontainer/devcontainer.json:
```
{
	"name": "Devcontainer Issues Repros",

	"dockerComposeFile": "./docker-compose.yml",

	"service": "app",

	"remoteEnv": {
		"DEV_CONTAINER_ID": "${devcontainerId}"
	},

	"features": {
		"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {}
	}
}
```

.devcontainer/docker-compose.yml:
```
version: '3'

services:
  app:
    image: ubuntu:20.04
    command: [ "sleep", "infinity" ]
```

OS: ubuntu 20.04
`docker --version`: `Docker version 23.0.1, build a5ee5b1`
`docker-compose --version`: `Docker Compose version v2.16.0`
`devcontainer --version`: `0.31.0`

This looks like a buildkit issue - intermediate images aren't being pushed to the local repository because buildkit is the default in docker 23. Everything works fine if I run with `DOCKER_BUILDKIT=0` in my env

Same issue occurs if I remove standalone docker-compose

**Comment by samruddhikhandale** [comment] 2023-03-03 17:28
Hi 👋 

I am able to make `devcontainer up --workspace-folder . --log-level debug` run successfully with these modified files 👇 

.devcontainer/devcontainer.json
```jsonc
{
	"name": "Devcontainer Issues Repros",

	"dockerComposeFile": "docker-compose.yml",
    "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
	"service": "app",

	"remoteEnv": {
		"DEV_CONTAINER_ID": "${devcontainerId}"
	},

	"features": {
		"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {}
	}
}
```

.devcontainer/docker-compose.yml
```
version: '3'

services:
  app:
    image: ubuntu:20.04
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
```

@NigelRook Can you retry with these file contents?

**Comment by chrmarti** [comment] 2023-03-08 06:47
What is the output of `docker buildx ls`? If you are using a custom builder please retry with the default by first running `docker buildx use default`.

This is likely a limitation with Docker Compose discussed in https://github.com/microsoft/vscode-remote-release/issues/7305#issuecomment-1293784565.

**Comment by NigelRook** [comment] 2023-03-08 11:10
```
❯ docker buildx ls
NAME/NODE       DRIVER/ENDPOINT             STATUS  BUILDKIT PLATFORMS
lucid_bhabha *  docker-container                             
  lucid_bhabha0 unix:///var/run/docker.sock running v0.11.3  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
default         docker                                       
  default       default                     running 23.0.1   linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

Running `docker buildx use default` does indeed make things work

**Comment by samruddhikhandale** [comment] 2023-03-08 19:31
Nice, closing as things are working it it. Feel free to reopen if needed, thanks!

**Closed by samruddhikhandale** 2023-03-08 19:31 UTC
Labels: info-needed

**Comment by felipecrs** [comment] 2023-03-30 23:26
But should not the devcontainer CLI pass in `--builder default` to ensure this does not happen?

**Comment by notpushkin** [comment] 2023-10-30 12:51
This is still an issue for me. I'm running Docker in [colima](https://github.com/abiosoft/colima/) on macOS, and to use the `default` builder I have to use a hacky workaround:

```
DOCKER_HOST=unix:///Users/ale/.colima/default/docker.sock devcontainer up --workspace-folder .
```

I beileve the root cause is the same as in https://github.com/microsoft/vscode-remote-release/issues/7305, so we can track the progress there. Maybe we should still reopen this issue for visibility though @samruddhikhandale?

**Comment by felipecrs** [comment] 2023-10-30 12:53
Perhaps `devcontainer cli` should pass `--load` to the `docker build` command, which will ensure to work even if the user has chosen to use a builder other than the `default`.

**Comment by notpushkin** [comment] 2023-10-30 13:10
@felipecrs It uses `docker-compose build` for Compose-based projects, so passing options directly wouldn't work here. Non-Compose-based projects already use additional contexts (the `--build-context` option) instead of a temporary image, so those should work out of the box.

Since Compose v1.17.0 [you can use additional contexts, too](https://github.com/compose-spec/compose-spec/pull/307), which would be a proper fix here IMO. (Maybe always building images with `docker build` would be even cleaner? That would be a pretty major refactoring though.)

**Comment by samruddhikhandale** [comment] 2023-10-31 23:41
@notpushkin Happy to reopen the issue, however, one quick check, does this following 👇 command work for you?

```
export DOCKER_HOST=unix:///Users/ale/.colima/default/docker.sock
docker buildx use default

```

By exporting/setting the `DOCKER_HOST` environment variable, I believe docker daemon should correctly look for the host.

**Comment by notpushkin** [comment] 2023-11-02 11:00
@samruddhikhandale That does work indeed, but _always_ using the default `docker` driver is undesirable as it [lacks some features](https://docs.docker.com/build/drivers/). For example, it can't build multiarch images, which probably is better done on CI only but realistically might be useful on a local machine from time to time.

Note that when `DOCKER_HOST` is set, buildx will automatically select the `default` builder (not sure if this is documented somewhere, just my observation):

```shell-session
$ DOCKER_HOST=unix:///Users/ale/.colima/default/docker.sock docker buildx ls
NAME/NODE DRIVER/ENDPOINT  STATUS  BUILDKIT PLATFORMS
colima    docker-container
  colima0 colima           stopped
default * docker
  default default          running 20.10.20 linux/arm64, linux/amd64
```

So you can just set `DOCKER_HOST` for a one-off command (like `devcontainer up` in my example above), but that's not a good user experience IMO.
