### ISSUE TITLE
Cannot pull features from private azure container registry

### ISSUE THREAD

**Issue by Clockwork-Muse** [devcontainers/cli#434] opened 2023-03-03 22:50 UTC
I'm currently unable to pull features from a private azure container registry when building containers.

I believe the accounts used should already have the proper permissions; at minimum, base images can be successfully pulled and used for the devcontainer.

The devcontainer is trivial
```json
{
    "name": "Sample",
    "image": "private.azurecr.io/alpine",
    "features": {
        "private.azurecr.io/devcontainers/features/hello:1": {}
    },
}
```

```log
$devcontainer build /tmp/somedir/ --log-level trace
devcontainer build /tmp/somedir/ --log-level trace
(node:274018) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
[11 ms] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.19.0-32-generic x64.
[11 ms] Start: Run: docker buildx version
[73 ms] Stop (62 ms): Run: docker buildx version
[74 ms] github.com/docker/buildx v0.10.2 00ed17d
[74 ms] 
[76 ms] Start: Run: docker inspect --type image private.azurecr.io/alpine
[114 ms] Stop (38 ms): Run: docker inspect --type image private.azurecr.io/alpine
[114 ms] Start: Run: docker inspect --type image private.azurecr.io/alpine
[152 ms] Stop (38 ms): Run: docker inspect --type image private.azurecr.io/alpine
[152 ms] local container features stored at: /home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/node_modules/vscode-dev-containers/container-features
[153 ms] Start: Run: tar --no-same-owner -x -f -
[167 ms] Stop (14 ms): Run: tar --no-same-owner -x -f -
[167 ms] workspace root: /tmp/somedir
[171 ms] Loaded /home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/node_modules/vscode-dev-containers/container-features/devcontainer-features.json, which declares 25 features and does not contain explicit source info.
[171 ms] --- Processing User Features ----
[171 ms] configPath: /tmp/somedir/.devcontainer/devcontainer.json
[171 ms] * Processing feature: private.azurecr.io/devcontainers/features/hello:1
[171 ms] > input: private.azurecr.io/devcontainers/features/hello:1
[171 ms] >
[171 ms] > resource: private.azurecr.io/devcontainers/features/hello
[171 ms] > id: hello
[171 ms] > version: 1
[171 ms] > owner: devcontainers
[171 ms] > namespace: devcontainers/features
[171 ms] > registry: private.azurecr.io
[171 ms] > path: devcontainers/features/hello
[172 ms] manifest url: https://private.azurecr.io/v2/devcontainers/features/hello/manifests/1
[530 ms] [httpOci] Attempting to authenticate via 'Bearer' auth.
[532 ms] [httpOci] Found auth for registry 'private.azurecr.io' in docker config.json
[532 ms] [httpOci] Attempting to fetch bearer token from:  https://private.azurecr.io/oauth2/token?service=private.azurecr.io&scope=repository:devcontainers/features/hello:pull
[758 ms] [-] HTTP request failed with status code 401: : Unauthorized
[758 ms] [httpOci] Could not fetch bearer token for 'private.azurecr.io': Error: HTTP 401: Unauthorized
[758 ms] [httpOci] ERR: Failed to fetch Bearer token from registry.
[758 ms] Request failed
[758 ms] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[758 ms] Github feature.
[758 ms] Could not resolve Feature 'private.azurecr.io/devcontainers/features/hello:1'.  Ensure the Feature is published and accessible from your current environment.
Error: Failed to process feature private.azurecr.io/devcontainers/features/hello:1
    at bne (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:3109)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async am (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:2243)
    at async Uf (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1853:1672)
    at async fm (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1853:207)
    at async foe (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:28181)
    at async loe (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:25018)
{"outcome":"error","message":"Failed to process feature private.azurecr.io/devcontainers/features/hello:1","description":"An error occurred building the container."}
```

**Comment by Clockwork-Muse** [comment] 2023-03-06 19:56
Okay....

The account(s) I'm using has access to the registry/repository.  I can push/pull images via docker.  I can pull artifacts via [oras](https://github.com/oras-project/oras).  In a CI scenario, with an account with some additional (although unknown) permissions, I can publish features, but not from my developer account.

Since oras is reusing my existing docker login, I'm leaning toward there being something about the token process on the azure side just... not being authorized for me.  Not sure whether this is due to something about the corporate setup, or if there's some other permission I need enabled.

**Comment by chrmarti** [comment] 2023-03-07 20:26
This is also a duplicate of https://github.com/devcontainers/cli/issues/349 or am I missing a subtle difference? We are not reading the `~/.docker/config.json` currently.

**Comment by Clockwork-Muse** [comment] 2023-03-07 21:11
... you do read the `~/.docker/config.json`, though?
```
[532 ms] [httpOci] Found auth for registry 'private.azurecr.io' in docker config.json
```
But no, I turned off the credential helper when I reported this issue (if it was on, that line would read "could not find....").

**Comment by chrmarti** [comment] 2023-03-08 09:40
You're right, we read `auths` from the Docker config. #349 is about using credential helpers too.

Are you using `auths` and that does not work? If so, could you append the config with sensitive information replaced with placeholders (such that the file structure remains the same).

**Comment by Clockwork-Muse** [comment] 2023-03-08 17:24
```shell
$ TOKEN=$(az acr login --name private --expose-token --output tsv --query accessToken)
$ echo $TOKEN | docker login private.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin
$ cat ~/.docker/config.json 
```
```json
{
	"auths": {
		"private.azurecr.io": {
			"auth": "somePrivateValue",
			"identitytoken": "someOtherPrivateValue"
		}
	}
}
```

That auth is sufficient for me to pull images (and the devcontainer cli will use docker to pull them), and oras can use it to pull the feature artifacts.  But when the devcontainer cli tries to use it to get a scope token it fails.

**Comment by joshspicer** [comment] 2023-03-09 18:46
Thanks for the feedback, I'll try to reproduce.  We have a test pulling from ACR in this repo, but that's against a public acr repo.

**Comment by chrmarti** [comment] 2023-03-10 10:03
I don't fully understand the Oras code, but it looks like it is using the `identitytoken` as a refresh token. Maybe Docker has documentation about this (couldn't find any on a quick search).

**Comment by joshspicer** [comment] 2023-03-13 18:10
Our parsing of the ~/.docker/config.json is fairly simple/naive.  It's only looking for that `auth` attribute and ignoring `identityToken`

https://github.com/devcontainers/cli/blob/main/src/spec-configuration/httpOCIRegistry.ts#L155

**Comment by Clockwork-Muse** [comment] 2023-03-13 19:19
... and the `auth` attribute is really short and repetitive in this case, I'm guessing it's probably the `0000-0....` "username" guid.

That aside, I think something else might be going on, too.  Using podman in wsl gives me a config file (at `/mnt/wsl/runtime-dir/containers/auth.json`) that looks like:

```json
{
    "auths": {
        "private.azurecr.io": {
            "auth": "somePrivateValue"
        }
    }
}
```
... and I can pull containers with that, but oras fails trying to get its own tokens:
```bash
oras pull private.azurecr.io/devcontainers/features:latest
Error: failed to resolve latest: GET "https://private.azurecr.io/v2/devcontainers/features/manifests/latest": GET "https://private.azurecr.io/oauth2/token?scope=repository%3Adevcontainers%2Ffeatures%3Apull&service=private.azurecr.io": response status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

**Comment by joshspicer** [comment] 2023-03-13 23:06
I _think_ a workaround would be to manually generated a repo token in the Azure CLI (see: https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions). That said, I definitely want to try to get it working with a simple `az acr login -n privatedevcontainercli`).

After creating a new container registry and pushing a single docker image to it (with docker cli), I can pull with oras provided I have logged in with `az acr`). Running oras with `--debug`, you can see that oras knows how to exchange the `identityToken` 

```
DEBU[0000]  Request URL: "https://privatedevcontainercli.azurecr.io/v2/ubuntu/manifests/latest" 
DEBU[0000]  Request method: "GET"                       
DEBU[0000]  Request headers:                            
DEBU[0000]    "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json" 
DEBU[0000]    "User-Agent": "oras/0.16.0"               
DEBU[0000]  Response Status: "401 Unauthorized"         
DEBU[0000]  Response headers:                           
DEBU[0000]    "Docker-Distribution-Api-Version": "registry/2.0" 
DEBU[0000]    "X-Content-Type-Options": "nosniff"       
DEBU[0000]    "Server": "openresty"                     
DEBU[0000]    "Strict-Transport-Security": "max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains" 
DEBU[0000]    "Content-Length": "200"                   
DEBU[0000]    "Connection": "keep-alive"                
DEBU[0000]    "Access-Control-Expose-Headers": "Docker-Content-Digest, WWW-Authenticate, Link, X-Ms-Correlation-Request-Id" 
DEBU[0000]    "Date": "Mon, 13 Mar 2023 22:57:56 GMT"   
DEBU[0000]    "Www-Authenticate": "Bearer realm=\"https://privatedevcontainercli.azurecr.io/oauth2/token\",service=\"privatedevcontainercli.azurecr.io\",scope=\"repository:ubuntu:pull\"" 
DEBU[0000]    "X-Ms-Correlation-Request-Id": "0f88351e-a7a9-4e6d-acbd-f8b8bd4bd021" 
DEBU[0000]    "Content-Type": "application/json; charset=utf-8" 
DEBU[0000]  Request URL: "https://privatedevcontainercli.azurecr.io/oauth2/token" 
DEBU[0000]  Request method: "POST"                      
DEBU[0000]  Request headers:                            
DEBU[0000]    "Content-Type": "application/x-www-form-urlencoded" 
DEBU[0000]    "User-Agent": "oras/0.16.0"               
DEBU[0000]  Response Status: "200 OK"                   
DEBU[0000]  Response headers:                           
DEBU[0000]    "Connection": "keep-alive"                
DEBU[0000]    "Strict-Transport-Security": "max-age=31536000; includeSubDomains" 
DEBU[0000]    "Server": "openresty"                     
DEBU[0000]    "Date": "Mon, 13 Mar 2023 22:57:56 GMT"   
DEBU[0000]    "Content-Type": "application/json; charset=utf-8" 
DEBU[0000]    "X-Ms-Correlation-Request-Id": "ccb705e5-4efb-486a-95c4-a562486a9615" 
DEBU[0000]    "X-Ms-Ratelimit-Remaining-Calls-Per-Second": "333.316667" 
DEBU[0000]  Request URL: "https://privatedevcontainercli.azurecr.io/v2/ubuntu/manifests/latest" 
DEBU[0000]  Request method: "GET"                       
DEBU[0000]  Request headers:                            
DEBU[0000]    "User-Agent": "oras/0.16.0"               
DEBU[0000]    "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json" 
DEBU[0000]    "Authorization": "*****"                  
DEBU[0000]  Response Status: "200 OK"                   
DEBU[0000]  Response headers:                           
DEBU[0000]    "Server": "openresty"                     
DEBU[0000]    "Content-Type": "application/vnd.docker.distribution.manifest.v2+json" 
DEBU[0000]    "Docker-Content-Digest": "sha256:12149a2b7cca0a69237b84c5d7a52bb7f7db451518ace6f4190800c003642bd9" 
DEBU[0000]    "X-Ms-Client-Request-Id": ""              
DEBU[0000]    "X-Ms-Correlation-Request-Id": "1da03f4b-4a60-4bb6-85f4-320c5e8d7e25" 
DEBU[0000]    "Access-Control-Expose-Headers": "Docker-Content-Digest, WWW-Authenticate, Link, X-Ms-Correlation-Request-Id" 
DEBU[0000]    "Docker-Distribution-Api-Version": "registry/2.0" 
DEBU[0000]    "Content-Length": "529"                   
DEBU[0000]    "X-Content-Type-Options": "nosniff"       
DEBU[0000]    "Date": "Mon, 13 Mar 2023 22:57:56 GMT"   
DEBU[0000]    "Connection": "keep-alive"                
DEBU[0000]    "Etag": "\"sha256:12149a2b7cca0a69237b84c5d7a52bb7f7db451518ace6f4190800c003642bd9\"" 
DEBU[0000]    "Strict-Transport-Security": "max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains" 
DEBU[0000]    "X-Ms-Request-Id": "ce732c0c-6e6b-4d39-a9ba-2bba352b8a61" 
Downloaded empty artifact
Pulled privatedevcontainercli.azurecr.io/ubuntu:latest
Digest: sha256:12149a2b7cca0a69237b84c5d7a52bb7f7db451518ace6f4190800c003642bd9
```

**Comment by joshspicer** [comment] 2023-03-13 23:20
Proxying the HTTPS request with mitmproxy, I can see how the identity token (`refresh_token`) here sends the JWT to the oauth endpoint. 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/23246594/224853533-3026aa9a-d1b2-4438-a46a-d34b8b8ed7a8.png">

I will work on implementing this pattern in the CLI.

**Comment by Clockwork-Muse** [comment] 2023-03-14 00:05
The user I'm using doesn't have access to create a permanent (potentially shared) token for the container registry... that's not what's causing the issue, is it?

(yes yes, I have ways to get around that, since I can write CI scripts to do that)

**Comment by joshspicer** [comment] 2023-03-14 00:07
No I don't think that's the issue, I think i'll be able to get it working with that refreshToken, as oras is doing ^

**Comment by joshspicer** [comment] 2023-03-14 00:57
@Clockwork-Muse CI is still running on this one, but I think this should help if you're interested in taking a look :)

**Comment by joshspicer** [comment] 2023-03-14 16:50
Let us know if build v0.33.0 helps!

**Comment by Clockwork-Muse** [comment] 2023-03-14 23:25
@joshspicer - Can confirm this works, thanks.

No to figure out how to get VS Code to use a custom build until the extension uses the new version...

**Comment by joshspicer** [comment] 2023-03-16 20:49
Until a new pre-release of the VS Code extension is released, you could probably use the CLI `up` command to bring up a workspace-folder's dev container, and then open it in VS Code.

**Comment by Clockwork-Muse** [comment] 2023-03-16 22:11
It turns out that it's possible to replace the version packaged in the extension by simply copying over the directories.

**Closed** 2023-03-27 16:43 UTC
Labels: bug
