### ISSUE TITLE
[Features] installsAfter is ignored, if a version is given

### ISSUE THREAD

**Issue by NicoVIII** [devcontainers/cli#269] opened 2022-11-05 11:51 UTC
If I define an installsAfter in a `devcontainer-feature.json` like this:
```
"installsAfter": [
    "ghcr.io/devcontainers/features/node"
]
```

It looks like this is honored, if I define the feature exactly like that
```
// Works
"ghcr.io/devcontainers/features/node": {}
```
but not if I define it with a version instead, e.g.
```
// Doesn't work
"ghcr.io/devcontainers/features/node:1": {},
```

To reproduce that, e.g. have a look at this scenario.json
https://github.com/NicoVIII/devcontainer-features/blob/96275e44d27abe90acf88a1378ff7646f45f9b54/test/pnpm/scenarios.json
The first two testcases work as expected, the last one, where I defined the version, didn't. You can look at that in the output of the GitHub Actions job (which is a bit crowded with all the docker output, but after a while you can see, that the first two scenarios succeeded, while the last one didn't):
https://github.com/NicoVIII/devcontainer-features/actions/runs/3399930614/jobs/5654000995#step:4:2058

Is this intended? I would have guessed, that installsAfter works for all versions, if I don't define one in there.

**Comment by metaskills** [comment] 2022-11-05 18:38
Thanks... I've been experience this too while developing some new internal features and was pulling my hair out.

**Comment by joshspicer** [comment] 2022-11-06 20:41
Thanks for raising and apologizes for the possible frustration.  This is how it is intended, since we don't currently want to commit to this amount of version-level dependencies until we can agree on the best approach for managing dependencies.

The docs should reflect that we are expecting a "version-less" Feature ID.  It does in the seciton above, but I will update the docs to reflect that for this property

cc/ @samruddhikhandale

**Comment by NicoVIII** [comment] 2022-11-07 07:22
Sorry, if I didn't understand you correctly or didn't describe the scenario good enough.
But my problem isn't that I use a version in installsAfter, but that I didn't use one in installsAfter but referenced one in the devcontainer.json.
And in this case the installsAfter doesn't seem to work.

```
...
// devcontainer-feature.json for pnpm feature
"installsAfter": [
    "ghcr.io/devcontainers/features/node"
]
...
```

```
// devcontainer.json - Works
...
"features": {
    "ghcr.io/devcontainers/features/node": {
        "version": "lts"
    },
    "pnpm": {}
}
...
```

```
// devcontainer.json - Doesn't work
...
"features": {
    "ghcr.io/devcontainers/features/node:1": {
        "version": "lts"
    },
    "pnpm": {}
}
...
```

**Comment by samruddhikhandale** [comment] 2022-11-07 21:56
If I am understanding it correctly, then looks like the issue occurs for the [version-bug](https://github.com/NicoVIII/devcontainer-features/blob/main/test/pnpm/scenarios.json#L20) scenario.

The author expects the `pnpm` Feature to be installed after `ghcr.io/devcontainers/features/node` Feature because of 👇 (which makes sense to me)

```
...
// devcontainer-feature.json for pnpm feature
"installsAfter": [
    "ghcr.io/devcontainers/features/node"
]
...
```

I tried to repro with `devcontainer features test ...` command and the I can see that the Compute Order is incorrect in the logs.

```
[2357 ms] --- Computed order ----
[2357 ms] ./pnpm
[2357 ms] ghcr.io/devcontainers/features/node:1
```

@joshspicer Could this be a bug in the `devcontainer features test` command ? 
 
I was able to successfully create a dev container as follows 👇 . The compute order was correct, so probably not a bug with `installsAfter` property? 🤔 

```
// .devcontainer.json
{
	"image": "ubuntu:latest",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"version": "lts"
		},
		"ghcr.io/nicoviii/devcontainer-features/pnpm:1": {}
	}
}
```

**Comment by metaskills** [comment] 2022-11-08 16:41
> but referenced one in the devcontainer.json.

This was my experience too. I had to remove the version from the feature user's `devcontainer.json` file where I was providing a version to the feature like this: `"ghcr.io/customink/features/vpn:1"`. Removing the `:1` allowed things to be ordered as expected.

> which should be allowed I believe...

That would be cool. Thank you!

**Comment by NicoVIII** [comment] 2022-12-09 06:37
I still have this problem and I don't have it only in the CLI tests but also when I try to use the feature in VScode directly.

devcontainer.json
```
{
	"name": "Debian",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {},
		"ghcr.io/NicoVIII/devcontainer-features/pnpm:1": {}
	}
}
```

Output:
```
Step 10/18 : RUN echo "_CONTAINER_USER_HOME=$(getent passwd root | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env && echo "_REMOTE_USER_HOME=$(getent passwd vscode | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env
[2022-12-09T06:35:59.031Z]  ---> Using cache
 ---> 5f9522ef9391
Step 11/18 : RUN cd /tmp/build-features/pnpm_2 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh
[2022-12-09T06:35:59.048Z]  ---> Running in c48c988d5f7b
[2022-12-09T06:35:59.267Z] ===========================================================================
Feature       : Pnpm
Description   : Installs pnpm, requires npm installed
Id            : ghcr.io/NicoVIII/devcontainer-features/pnpm
Version       : 1.0.0
Documentation : 
Options       :
    VERSION="latest"
===========================================================================
[2022-12-09T06:35:59.268Z] ./install.sh: 5: npm: not found
Try to install pnpm with version 'latest'
[2022-12-09T06:35:59.268Z] ERROR: Feature "Pnpm" (ghcr.io/NicoVIII/devcontainer-features/pnpm) failed to install!
[2022-12-09T06:35:59.454Z] The command '/bin/sh -c cd /tmp/build-features/pnpm_2 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh' returned a non-zero code: 127
[2022-12-09T06:35:59.458Z] Stop (13506 ms): Run: docker build --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-test-67cea80c5a3bdd6cf76ac7afa2f531b4-features -f /tmp/devcontainercli-nico/container-features/0.25.2-1670567743115/Dockerfile.extended /home/nico/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2022-12-09T06:35:59.460Z] Error: Command failed: docker build --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-test-67cea80c5a3bdd6cf76ac7afa2f531b4-features -f /tmp/devcontainercli-nico/container-features/0.25.2-1670567743115/Dockerfile.extended /home/nico/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2022-12-09T06:35:59.460Z]     at Aoe (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1355)
[2022-12-09T06:35:59.461Z]     at uT (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1291)
[2022-12-09T06:35:59.462Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-12-09T06:35:59.462Z]     at async Poe (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[2022-12-09T06:35:59.463Z]     at async Zf (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[2022-12-09T06:35:59.464Z]     at async aue (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[2022-12-09T06:35:59.465Z]     at async oue (/home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[2022-12-09T06:35:59.473Z] Stop (16590 ms): Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/nico/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/nico/Schreibtisch/test --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/nico/Schreibtisch/test --log-level debug --log-format json --config /home/nico/Schreibtisch/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-12-09T06:35:59.474Z] Exit code 1
[2022-12-09T06:35:59.478Z] Command failed: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/nico/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/nico/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/nico/Schreibtisch/test --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/nico/Schreibtisch/test --log-level debug --log-format json --config /home/nico/Schreibtisch/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-12-09T06:35:59.479Z] Exit code 1
```

**Comment by chrmarti** [comment] 2023-01-13 09:09
@joshspicer This is reported as not working correctly (https://github.com/microsoft/vscode-remote-release/issues/7838), could you take a look? (I see your spec update.)

**Comment by joshspicer** [comment] 2023-02-06 23:27
I believe this has been fixed with https://github.com/devcontainers/cli/commit/dc23b12bafc8fa0eac43fb1b1daccef8ba17ce82#diff-5d796ceb58c276912ce5289b37ea9eda883f4abbf9b6cc1252661deccae91e67R52

I can not repro with a similar example - please do reopen if you find another repro. Thanks!

**Closed by joshspicer** 2023-02-06 23:27 UTC
