### ISSUE TITLE
Redundant Dockerfile required in order to push to correct repo

### ISSUE THREAD

**Issue by AvishayHirsh** [devcontainers/cli#791] opened 2024-04-02 15:48 UTC
Using 0.58 version : 

1. Create devcontainer.json 
```javascript
{
  "image":"mcr.microsoft.com/devcontainers/base:ubuntu",
  "features": {
    "ghcr.io/devcontainers/features/node:1": {
      "version": "16.18.1"
    },
    "ghcr.io/devcontainers-contrib/features/bash-command:1": {
      "command": "pip3 install jinja2 PyYAML"
    }
  }
} 

``` 
2. Build and try push to your repository : 

```shell
devcontainer --log-level trace --workspace-folder . build --config devcontainer.json --image-name <YourCustomRepo>:<YourCustomTag>  --platform linux/arm64,linux/amd64 --push true
```  

This Results with : 

```typescript

exporting to image:

ERROR: failed to solve: failed to push docker.io/library/vsc-base-image-360ebb83a1aa22c95928798ea8b92eedca9aac8ca2cc4a873ab7b5223cedfebd-features:latest: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 

``` 
**Expected: build is successfull and pushed to custom repo in registry.
Actual: It seems to try push to ibrary/vsc-base-image instead of my repo, and fails**  

When i replace the image property with build to Dockerfile which has the image inside it, it just works : 

```typescript
{
  "build": {
    "dockerfile": "Dockerfile"
  },
  "features": {
    "ghcr.io/devcontainers/features/node:1": {
      "version": "16.18.1"
    },
    "ghcr.io/devcontainers-contrib/features/bash-command:1": {
      "command": "pip3 install jinja2 PyYAML"
    }
  }
}
``` 

Dockerfile : 

```dockerfile
FROM mcr.microsoft.com/devcontainers/base:ubuntu
``` 

it works and pushes to the custom repo as required.

**Comment by samruddhikhandale** [comment] 2024-04-04 22:24
Hi 👋 

Thanks for opening this issue, I was able to reproduce this as well.

> Actual: It seems to try push to ibrary/vsc-base-image instead of my repo, and fails

When the dev container is built with an `image` property, it is pushing an incorrect image. This definitely looks like a bug. // cc @chrmarti

**Comment by samruddhikhandale** [comment] 2024-04-04 22:25
@gauravsaini04 Can you help prioritize fixing this issue?

**Comment by AvishayHirsh** [comment] 2024-04-07 10:29
@samruddhikhandale btw seems to be same as https://github.com/devcontainers/cli/issues/370

**Comment by prathameshzarkar9** [comment] 2024-04-26 07:15
Hi @samruddhikhandale ,

I have created a PR https://github.com/devcontainers/cli/pull/812
if user procide the `--image-name` then this specific name will be used to push the docker image with the build command.
but if we do not pass the `--image-name` then it is using `cli-generated-image` to push to image and it is failing with the below error:
```
{
  "outcome": "error",
  "message": "Command failed: docker buildx build --platform linux/amd64 --push --build-context dev_containers_feature_content_source=/tmp/devcontainercli-node/container-features/0.59.1-1714115121385 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-example-push-ca34dc0eddd392c65ec666bc1f7466ba3bc4760f9ef20a68674a2f9a7405218f-features -f /tmp/devcontainercli-node/container-features/0.59.1-1714115121385/Dockerfile.extended /tmp/devcontainercli-node/empty-folder",
  "description": "An error occurred building the container."
}
```

**Comment by samruddhikhandale** [comment] 2024-04-26 19:33
Awesome, thanks @prathameshzarkar9! Reviewing the PR now.

>  if we do not pass the --image-name then it is using cli-generated-image to push to image and it is failing with the below error:

That's alright, anyone who wants to publish the image would have to make sure they have logged into the appropriate registries.

**Comment by prathameshzarkar9** [comment] 2024-04-29 03:53
Hi @samruddhikhandale ,
review comments addressed, kindly confirm and merge if the changes make sense.

**Comment by samruddhikhandale** [comment] 2024-05-28 23:06
Closing as completed with https://github.com/devcontainers/cli/pull/812

**Closed by samruddhikhandale** 2024-05-28 23:06 UTC
Labels: bug
